### ISSUE TITLE
clear ordering on third click

### ISSUE THREAD

**Issue by ouven** [woylie/flop_phoenix#156]
# Problem

I cannot clear a sorting on a column

# maybe Solution

* click once: order asc 
* second click: order desc
* third click: clear

**Comment by woylie** [comment]
I think that has come up before.

The table can be sorted by multiple columns. Clicking the column header prepends that column to the order. If you go from asc to desc to unsorted, this would mean that the first field would be removed from the order, in which case the table would now be sorted by the second field in the order list. This might be unexpected and confusing.

The table component is commonly used in combination with pagination, which means there _has_ to be a default order, or otherwise the pagination doesn't make sense. This means that if you were to allow to clear the sort order as proposed, you could end up with a table without any order-by conditions, in which case the order of the result set would be nondeterministic and the pagination would be broken.

Since you already need a default order, all you have to do to go back to the original order is to click the column header of the default order-by field.
