### ISSUE TITLE
Grouping columns for conditional rendering

### ISSUE THREAD

**Issue by JayKim94** [woylie/flop_phoenix#193]
### - Issue description -

First of all, thanks to your hard work, I was able to solve multiple problems that I had with table component(pagination, ordering/sorting all-in-one).

The only issue I am currently experiencing is the readability and maintainability of codes on the template(.heex), especially when I have a various items in a single table which share the same schema, that need conditional rendering depending on its attribute.

Let me give you an example to better illustrate what I mean:

#### Setting
- Think of a table, let's say for the schema of `RowItem`
- Table has columns of `:name`, `:updated_at`, `:deleted_at`
- `RowItem` has an attribute, `is_deleted`

#### What need to be done
- If `RowItem.is_deleted` is true, we should render values for `:name`, `:updated_at` columns, others left empty
- If `RowItem.is_deleted` is false, we should render values for `:name`, `:deleted_at` columns, others left empty

For this kind of situation we'd have to repeat the same control structure(If/case, etc.) inside every `:col` slot, and this develops quickly into a mess as the number of columns grow.

### - Suggested solution -

It would be cool to have a clean & readable way to put the columns(`:col` slots) into groups, to **conditionally** render them for each row, depending on the current `item`. See the alternative solution below that I created(but not good enough), to get the better idea of what I am saying.

### - Alternative solution - 

I've tried to create an extra slot called `:col_group`, which basically just takes the list of what `:col` slot would receive as attributes, and clone them(based on the number of fields given to `:col_group`) with the same `inner_block` function.

There is a lot of custom logic behind to make this work(which is pretty hard to explain, therefore not a good logic), so let me show you how it would look on the template:

```elixir
<:col_group
  :let={entry}
  show?={fn item -> is_nil(item.is_deleted) end}
  labels={["Name", "Updated at"]}
  fields={[:name, :updated_at]}
>
  <%= case %{item: item} = entry do %>
    <% %{field: :name} -> %>
      <span><%= item.name %></span>
    <% %{field: :inserted_at} -> %>
      <span><%= item.inserted_at %></span>
    <% _ -> %>
  <% end %>
</:col_group>
<:col_group 
  :let={entry} 
  show?={fn item -> item.deleted_at end} 
  labels={["Name", "Deleted at"]} 
  fields={[:name, :deleted_at]}
>
  <%= case %{item: item} = entry do %>
    <% %{field: :name} -> %>
      <span><%= item.name %></span>
    <% %{field: :deleted_at} -> %>
      <span><%= item.deleted_at %></span>
    <% _ -> %>
  <% end %>
</:col_group>
```

While this approach works(also in combination with classic `:col` slots), it did not improve the readability nor maintainability. Also this still entails a lot of control structure in the template, which we would like to avoid as much as possible.

If you already have a better idea how to improve readability by any means other than this topic, feel free to suggest. Just want to explore what kind of possibilities are out there, thanks! 👍

**Comment by woylie** [comment]
I wouldn't know a good API for making this possible that is still readable and understandable. Sometimes it's better to be explicit than to be clever at the cost of a murky API.

Logically, the control structure should be _within_ the `<:col>`, not _on_ the `<:col>`, since in your example, the content of the columns depends on the individual item, not on some global condition. We always want to show the same number of columns, and the column header should match whatever variation can be rendered in the columns. Staying with your example, this should look like this:

```elixir
<:col :let={i} field={:name} label="Name>
  <%= i.name %>
</:col>
<:col :let={i} label="Timestamp">
  <%= if i.deleted_at do %>
    <%= DateTime.to_string(i.deleted_at) %>
  <% else %>
    <%= DateTime.to_string(i.updated_at) %>
  <% end %>
</:col>
```

Note that you can't put the `field` attribute on the second column, since the displayed value depends on the item.

Even with more columns, I would find that perfectly fine and clear. If you don't like the `if`s in the template, you can also create a helper function and use pattern matching instead.

```elixir
defp column(:timestamp, %Item{deleted_at: nil, updated_at: ts}), do: ts
defp column(:timestamp, %Item{deleted_at: ts}), do: ts

<:col :let={i} field={:name} label="Name>
  <%= i.name %>
</:col>
<:col :let={i} label="Timestamp">
  <%= column(:timestamp, i) %>
</:col>
```

Or if your column content requires additional markup, that helper function could be replaced by a function component with similar pattern matching.

**Comment by JayKim94** [comment]
Come to think of it, you made a good point there with being explicit. I think I was too into creating precisely-purpose-serving API for this, but with some clean-ups I see your point.

Thank you so much for your feedback!
