### ISSUE TITLE
Support richer column headings in Flop.Phoenix.table

### ISSUE THREAD

**Issue by wodow** [woylie/flop_phoenix#194]
I sometimes wish to use HTML elements such as `<attr>` within column headings, but currently `<:col label>` accepts strings only.

I'm not sure what the best approach/API would be for this. Can `<:col>` take a slot of its own (a "sub-slot"?), such as  `<:label>` ?

**Comment by wodow** [comment]
I now realise using `Phoenix.HTML.raw()` would work for the simplest cases here, since the `label` attr doesn't _strictly_ require string-binaries.

**Comment by woylie** [comment]
LiveView doesn't support "sub-slots". You can use `raw` indeed, or the functions from [Phoenix.HTML.Tag](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Tag.html) (this would be one of those "special circumstances" mentioned in the docs then). The only alternative would be to separate the `label` from the `:col` slot and introduce a new `:th` slot, but that would also introduce room for error, since then it's easy for columns and column headers getting out of sync.
