### ISSUE TITLE
build_path: remove _target from query params

### ISSUE THREAD

**Issue by woylie** [woylie/flop_phoenix#205]

**Comment by vanderhoop** [comment]
Including the `_target` is the default behavior of LiveView forms, and can be useful for pattern matching against different `events` events in a LiveView. For example, we're using it to pattern match the filter form's `reset` input (rather than having a separate button and event), as a reset input fires a change event on the form data.

`_target`'s inclusion in the url is admittedly not the prettiest, but maybe it should be opt-out, rather than removed altogether?

**Comment by woylie** [comment]
I updated the filter form example to just drop the `_target` parameter before patching the URL. I also changed the filter reset to use an actual reset button, thanks for the trigger.
