### ISSUE TITLE
add examples for using streams

### ISSUE THREAD

**Issue by woylie** [woylie/flop_phoenix#207]

**Comment by suranyami** [comment]
Do we have any rough examples? I'd be happy to write up the docs if someone can give me a working example.

I tried to get it to work with code like this:

```elixir
  def handle_params(params, _url, socket) do
    with {:ok, {transactions, meta}} <- Transactions.list_page(params),
      socket = assign(socket, meta: meta)
      {:noreply, stream(socket, transactions: transactions)}
    end
```

And then this in the HEEX file:

```eex
<Flop.Phoenix.table items={@stream.transactions} meta={@meta} path={~p"/transactions"}>
```

But it choked because `@stream.transactions` returns a tuple:

```elixir
{"transaction-1", %Transaction{x: 1, y: 2}}
```

I presume the first item is the DOM ID, but not sure where it needs to end up?

**Comment by woylie** [comment]
That looks nearly correct, except that you would need to reset the stream, unless you want to keep adding items without removing old ones. I have something like this in a project:

```elixir
  def handle_params(params, _url, socket) do
    {:ok, {pets, meta}} =
      Clients.list_pets(params)

    {:noreply,
     socket
     |> assign(:meta, meta)
     |> stream(:pets, pets, reset: true)}
  end
```

And:

```elixir
<.table items={@streams.pets} meta={@meta} path={~p"/pets"}>
  <:col :let={{_, pet}} label="Name" field={:name}>
    <%= pet.name %>
  </:col>
</.table>
```

Notice that you need to match on a tuple in the `:let` attribute when you are using with streams.
