### ISSUE TITLE
Provide a mechanism to pass in additional querystring params to page link helpers for sorting, pagination, and filtering

### ISSUE THREAD

**Issue by jesse-iluminai** [woylie/flop_phoenix#24]
**Is your feature request related to a problem? Please describe.**
I need to pass in additional querystring params keys and values to pagination and sorting helpers so that I can maintain state on GET calls.

I'm blocked adding new features for lists that need to send params through to control their visibility and filter tweaking as they get reset/dropped when the user attempts to paginate or sort.

**Describe the solution you'd like**
Ideally a simple way to specify keys and values that should be included in the page link builder to the server along with the handled page=1&page_size=15 params that are submitted.

It might be nice also that instead of the whitelist of params that Flop Phoenix builds for its helper links that it includes any other querystring params sent by the server on the last request.  It seems that the params that are being built are explicit and only concern the page link helpers.

That do you think Mattias?

**Comment by woylie** [comment]
You can pass additional query parameters as part of the route helper args to all functions, see the last example here: https://hexdocs.pm/flop_phoenix/Flop.Phoenix.html#build_path/3.

**Comment by woylie** [comment]
I'll close this, since it is already possible to pass additional query parameters. I don't think passing any parameters from last request would be a good idea. The Flop Phoenix functions currently don't take the `Plug.Conn` as a parameter. The path helper function passed to the functions is called with the path helper arguments that are passed without making any assumptions about them. We don't know whether the first argument is a conn or a socket. If it's a conn, we don't know whether which parameters we should take. Only the query parameters? What if the request was made with POST and body parameters (e.g. passed by a filter form)? If it is a LiveView socket, the original params aren't even part of it.
