### ISSUE TITLE
Increase customization of table generator

### ISSUE THREAD

**Issue by MMore** [woylie/flop_phoenix#29]
**Is your feature request related to a problem? Please describe.**
This relates to the general intent of #26 to improve compatibility with Tailwind. I have a table where I am styling the `tr` tags with some css classes. flop_phoenix does not allow customization of `tr` tags right now. Moreover I have some styling classes for the `td` tags in header and body. For the header I could just pass my markup to the `headers` key. But then I need to reimplement building a sorting link + direction indicator. For the body I can't pass any `td` styling classes right now.

**Describe the solution you'd like**
Allow addings attributes to `tr` and `td` tags. A helper for sorting links with direction indicator in addition to `build_path/3` might be beneficial.

**Describe alternatives you've considered**
Right now I am not using the `table` generator but just my own markup with an own reimplemented sortable link builder with direction indicator.

**Comment by woylie** [comment]
I guess we could add the options `thead_tr_attrs`, `thead_td_attrs`, `tbody_tr_attrs` and `tbody_td_attrs`. Although adding the same classes to every single `<tr>` and `<td>` tag will create a pretty bloated HTML output. But I guess if you're using Tailwind, you don't care about that kind of things.

On an unrelated note, maybe a `table_footer` option could be useful, too. Same as `table_headers`, but takes the complete result list as an argument, so that you can build column totals or similar.

**Comment by MMore** [comment]
Yeah, indeed. At least having those 4 parameters as optional arguments does not bother people who are not using tailwind.
An alternative is just providing a helper for creating a sortable link including direction indicator. So I can just continue using my HTML table. That would be fine as well for me.

**Comment by MMore** [comment]
Hey @woylie, thank you for your quick adjustments! I've just tried the new customization options for my tables and noticed that it does not fit for me. The problem is that I have tables where the cell styling is partly quite different. For instance I have tables with an action table cell which is different to other cells. Sure, I could just do some styling in a child `span`/`div` of the `td` tag, but it does not feel right for me.

So I think I will just stay with my pure HTML code in the template and my self-made sortable function. That works better for me, because I don't need to build another "DSL" on top of just building a simple table.

**Comment by woylie** [comment]
> One problem is that I have tables where the cell styling is partly quite different. 

Why didn't you say so right away? 😅 

For different column attributes, I could imagine several solutions. 

1. The row builder function could be allowed to return a tuple `{attrs, content}` for  a column instead of just the column.
2. There could be another `row_attrs_builder` option.
3. The `tbody_td_attrs` option could be allowed to be a function that takes the index of the column as an argument.

Giving an ID to the rows would require a `tr_attrs_builder` function that takes the item as an argument. But this seems like a very uncommon use case.

I don't think I'm going to implement any of this any time soon.

**Comment by MMore** [comment]
I am sorry. Sometimes you notice such things when you start using it.

What do you think about just providing a helper for a sortable link of the table head? Like `sortable_link(title, field_name, flop_meta)`. So you don't need to handle every complex case a consumer of your library might have. So I can just continue using my (slightly more complex) table as HTML.

**Comment by woylie** [comment]
Yes, that's possible.
