### ISSUE TITLE
Support Bootstrap style pagination

### ISSUE THREAD

**Issue by fcarlislehg** [woylie/flop_phoenix#79]
Bootstrap uses a `ul` and `li` for all parts of the pagination items. The order of next, previous, and list matter.

```
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</nav>
```
https://getbootstrap.com/docs/5.0/components/pagination/

The pagination is very configurable but I didn't see how I could configure it to generate the necessary markup.

Thanks for your consideration and happy to contribute given some guidance.

**Comment by woylie** [comment]
Hey @fcarlislehg, thanks for the feature request. To be honest, I wouldn't know how an API for this should look like. I also don't think we should add a markup variant just because some CSS framework uses it (there are a lot of those). The current markup gives you all the flexibility to render the pagination in any way you want (previous/pages/next, next/pages/previous, previous/next/pages, pages/previous/next ...), with just a little bit of CSS.

**Comment by forest** [comment]
I agree it should not be css framework specific. I missed how to configure it to render previous/pages/next. I'll take another look.

**Comment by woylie** [comment]
Here's an example for changing the order:

```css
.pagination {
  display: flex;
}

.pagination-list {
  order: 2;
}

.pagination-previous {
  order: 1;
}

.pagination-next {
  order: 3;
}
```
